### ISSUE TITLE
Lagrange (chebyshev) polynomial KAN

### ISSUE THREAD

**Issue by jloveric** [mintisan/awesome-kan#16]
The approach used in this repo https://github.com/jloveric/high-order-layers-torch is piecewise polynomial using lagrange polynomials (both continuous and discontinuous). This repo was made in 2020, so it doesn't have the KAN name. It also has hp refinement implemented (at least for non convolutional layers). The links within that repo show it's application to implicit representation, nlp, euler equations (pdes) and a number of other applications with varying level of success.

**Comment by mintisan** [comment]
It looks like this, I have added it to the alternative project.
