### ISSUE TITLE
Add Tutorial

### ISSUE THREAD

**Issue by team-daniel** [mintisan/awesome-kan#32]
You have my tutorial GitHub repo on here.

I have a complementary blog post that explains KANs in layman's terms. 

-> [https://daniel-bethell.co.uk/posts/kan](https://daniel-bethell.co.uk/posts/kan)

Thanks :)

**Comment by mintisan** [comment]
Thank you very much, I have manually added it. You can open a pull request later, which will make it easier for me to merge.
