### ISSUE TITLE
Include more efficient CUDA implementation 

### ISSUE THREAD

**Issue by Da1sypetals** [mintisan/awesome-kan#42]
I wonder if this repo can include more CUDA implementation which are more efficient to build a comparison between MLP (which are highly optimized in frameworks) and explore the performance limit of KAN with more optimizations.

I am a CUDA beginner and have implemented several types of KAN layers for practice purposes, and I am very curious about the performance aspect of KAN.

This may also attract someone professional in kernel optimization to explore on this topic.

My implementations:
- https://github.com/Da1sypetals/cuda-Wavelet-KAN
- https://github.com/Da1sypetals/cuda-Wavelet-KAN

**Comment by mintisan** [comment]
merged, thanks.
