### ISSUE TITLE
Suggestion to add KANQAS as recently developments with KAN

### ISSUE THREAD

**Issue by Aqasch** [mintisan/awesome-kan#79]
I would like to highlight our recent paper KANQAS. Where we utilize KAN for quantum architecture search. It would be appreciated if you add our work: https://github.com/Aqasch/KANQAS_code/tree/main and paper: https://arxiv.org/abs/2406.17630. Thanks!

**Comment by mintisan** [comment]
thanks, you can send a PR directly.XD

**Comment by Aqasch** [comment]
Thanks will do!
