### ISSUE TITLE
Kolmogorov-Arnold Transformer

### ISSUE THREAD

**Issue by Adamdad** [mintisan/awesome-kan#91]
We've just released a new paper on integrating Transformers with KAN. Check out the paper and feel free to explore our code repository!

📄 Paper: https://arxiv.org/abs/2409.10594
💻 Code: https://github.com/Adamdad/kat

**Comment by mintisan** [comment]
hi @Adamdad can you send a pr? Thanks.

**Comment by Adamdad** [comment]
Yes. Can see my twitter https://x.com/yxy2168/status/1836222025565897210 or the twitter from AK  https://x.com/_akhaliq/status/1836215243888038024. If you need a new version, please let me know. Thank you!
